CompiledPackageInfo {
    package_name: "Root",
    address_alias_instantiation: {
        "A": 0x00000000000000000000000000000001,
    },
    module_resolution_metadata: {
        ModuleId {
            address: 0x00000000000000000000000000000001,
            name: Identifier(
                "B",
            ),
        }: "A",
        ModuleId {
            address: 0x00000000000000000000000000000001,
            name: Identifier(
                "Example",
            ),
        }: "A",
        ModuleId {
            address: 0x00000000000000000000000000000001,
            name: Identifier(
                "OneDep",
            ),
        }: "A",
    },
    source_digest: Some(
        "ELIDED_FOR_TEST",
    ),
    build_flags: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
        additional_named_addresses: {},
    },
}
